# Generated by Django 6.0.3 on 2026-04-04 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("viewer", "Viewer"),
                            ("analyst", "Analyst"),
                            ("admin", "Admin"),
                        ],
                        help_text="Role identifier: viewer, analyst, or admin",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of role and its permissions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Unique username for login",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="User's email address", max_length=254, unique=True
                    ),
                ),
                (
                    "password",
                    models.CharField(help_text="Hashed password", max_length=255),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this user account is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        help_text="User's role (determines permissions)",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance_app.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount (must be positive)",
                        max_digits=12,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Income"), ("expense", "Expense")],
                        help_text="Type of transaction: income or expense",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("bonus", "Bonus"),
                            ("investment", "Investment"),
                            ("food", "Food & Dining"),
                            ("transportation", "Transportation"),
                            ("utilities", "Utilities"),
                            ("entertainment", "Entertainment"),
                            ("health", "Health & Fitness"),
                            ("education", "Education"),
                            ("shopping", "Shopping"),
                            ("other", "Other"),
                        ],
                        help_text="Category of transaction",
                        max_length=50,
                    ),
                ),
                ("date", models.DateField(help_text="Date of transaction")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description or notes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Soft delete timestamp (null if not deleted)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this transaction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="finance_app.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["username"], name="finance_app_usernam_c2522d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="finance_app_email_06b0cb_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "-date"], name="finance_app_user_id_73457e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["type"], name="finance_app_type_22af27_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["category"], name="finance_app_categor_c952ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["deleted_at"], name="finance_app_deleted_e9739a_idx"
            ),
        ),
    ]
